# Generated by Django 4.0.3 on 2022-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('EXE', 'EXECUTIVE'), ('DEL', 'DELUXE'), ('PRE', 'PREMIUM'), ('STD', 'STANDARD'), ('PNT', 'PENTHOUSE')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
